# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload to App Store"
  lane :release do
    # Update build number
    increment_build_number(xcodeproj: "App.xcodeproj")
    
    # Set up code signing
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "App.xcodeproj",
      team_id: ENV["TEAM_ID"],
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV["PROVISIONING_PROFILE_NAME"]
    )
    
    # Build the app with explicit code signing
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "io.coreykarnei.RipWise" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      }
    )
    
    # Upload to App Store
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      force: true
    )
  end
end
